# Generated by Django 4.2.3 on 2023-07-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding_question',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
