# Generated by Django 4.2.3 on 2023-07-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturaApp', '0002_coding_question_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coding_question',
            name='status',
        ),
    ]
