# Generated by Django 4.2.3 on 2023-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturaApp', '0003_remove_coding_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding_question',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
